# Generated by Django 5.1.3 on 2025-01-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("white", "White"),
                    ("orange", "Orange"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("pink", "Pink"),
                    ("yellow", "Yellow"),
                ],
                default="green",
                help_text="Name of the avatar. It will be obtained from the frontend statics.",
                max_length=255,
                verbose_name="Avatar name",
            ),
        ),
    ]
