# Generated by Django 5.1.7 on 2025-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("google", "Google")],
                default="email",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("white", "White"),
                    ("orange", "Orange"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("pink", "Pink"),
                    ("yellow", "Yellow"),
                ],
                default="green",
                help_text="Name of the avatar. It will be obtained from the frontend statics.",
                max_length=255,
                null=True,
                verbose_name="Avatar name",
            ),
        ),
    ]
