# Generated by Django 5.1.3 on 2024-12-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionlevelcategory",
            name="order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Order of the question in the level and category.",
                null=True,
                verbose_name="Order",
            ),
        ),
    ]
