# Generated by Django 5.1.3 on 2025-01-01 13:11

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_questionlevelcategory_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "reaction",
                    models.CharField(
                        choices=[("LIKE", "Like"), ("DISLIKE", "Dislike"), ("FAVORITE", "Favorite")],
                        default="LIKE",
                        help_text="Reaction of the user to the question.",
                        max_length=255,
                        verbose_name="Reaction",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question the user has reacted to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that has reacted to the question.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        related_query_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question reaction",
                "verbose_name_plural": "Question reactions",
            },
        ),
    ]
