# Generated by Django 5.1.3 on 2025-01-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_questionreaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionreaction",
            name="question",
            field=models.ForeignKey(
                help_text="Question the user has reacted to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                related_query_name="reactions",
                to="questions.question",
                verbose_name="Question",
            ),
        ),
    ]
