# Generated by Django 5.1.3 on 2025-01-02 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_questionreaction_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionreaction",
            unique_together={("question", "user", "reaction")},
        ),
    ]
