# Generated by Django 5.1.3 on 2025-01-07 15:03

import core.helpers.storage_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_questionreaction_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Category icon",
                null=True,
                upload_to=core.helpers.storage_helpers.handle_storage,
                verbose_name="Icon",
            ),
        ),
    ]
